use super::card::{CardAbility, CardColor, CardCost, CardTier, JewelCard, RoyalAbility, RoyalCard};

/// 全套 67 张珠宝卡静态数据库
pub const ALL_JEWEL_CARDS: [JewelCard; 67] = [
    JewelCard {
        id: 0,
        tier: CardTier::Tier1,
        color: CardColor::Black,
        points: 0,
        bonus: 1,
        ability: None,
        crowns: 0,
        cost: CardCost::new(1, 1, 1, 1, 0, 0),
    },
    JewelCard {
        id: 1,
        tier: CardTier::Tier1,
        color: CardColor::Black,
        points: 0,
        bonus: 1,
        ability: Some(CardAbility::ExtraTurn),
        crowns: 0,
        cost: CardCost::new(2, 2, 0, 0, 0, 1),
    },
    JewelCard {
        id: 2,
        tier: CardTier::Tier1,
        color: CardColor::Black,
        points: 0,
        bonus: 1,
        ability: Some(CardAbility::TakeSameColor),
        crowns: 0,
        cost: CardCost::new(0, 0, 2, 2, 0, 0),
    },
    JewelCard {
        id: 3,
        tier: CardTier::Tier1,
        color: CardColor::Black,
        points: 1,
        bonus: 1,
        ability: None,
        crowns: 0,
        cost: CardCost::new(0, 2, 3, 0, 0, 0),
    },
    JewelCard {
        id: 4,
        tier: CardTier::Tier1,
        color: CardColor::Black,
        points: 0,
        bonus: 1,
        ability: None,
        crowns: 1,
        cost: CardCost::new(3, 0, 0, 0, 0, 0),
    },
    JewelCard {
        id: 5,
        tier: CardTier::Tier1,
        color: CardColor::Red,
        points: 0,
        bonus: 1,
        ability: None,
        crowns: 0,
        cost: CardCost::new(1, 1, 1, 0, 1, 0),
    },
    JewelCard {
        id: 6,
        tier: CardTier::Tier1,
        color: CardColor::Red,
        points: 0,
        bonus: 1,
        ability: Some(CardAbility::ExtraTurn),
        crowns: 0,
        cost: CardCost::new(2, 0, 0, 0, 2, 1),
    },
    JewelCard {
        id: 7,
        tier: CardTier::Tier1,
        color: CardColor::Red,
        points: 0,
        bonus: 1,
        ability: Some(CardAbility::TakeSameColor),
        crowns: 0,
        cost: CardCost::new(0, 2, 2, 0, 0, 0),
    },
    JewelCard {
        id: 8,
        tier: CardTier::Tier1,
        color: CardColor::Red,
        points: 1,
        bonus: 1,
        ability: None,
        crowns: 0,
        cost: CardCost::new(2, 3, 0, 0, 0, 0),
    },
    JewelCard {
        id: 9,
        tier: CardTier::Tier1,
        color: CardColor::Red,
        points: 0,
        bonus: 1,
        ability: None,
        crowns: 1,
        cost: CardCost::new(0, 0, 0, 0, 3, 0),
    },
    JewelCard {
        id: 10,
        tier: CardTier::Tier1,
        color: CardColor::Green,
        points: 0,
        bonus: 1,
        ability: None,
        crowns: 0,
        cost: CardCost::new(1, 1, 0, 1, 1, 0),
    },
    JewelCard {
        id: 11,
        tier: CardTier::Tier1,
        color: CardColor::Green,
        points: 0,
        bonus: 1,
        ability: Some(CardAbility::ExtraTurn),
        crowns: 0,
        cost: CardCost::new(0, 0, 0, 2, 2, 1),
    },
    JewelCard {
        id: 12,
        tier: CardTier::Tier1,
        color: CardColor::Green,
        points: 0,
        bonus: 1,
        ability: Some(CardAbility::TakeSameColor),
        crowns: 0,
        cost: CardCost::new(2, 2, 0, 0, 0, 0),
    },
    JewelCard {
        id: 13,
        tier: CardTier::Tier1,
        color: CardColor::Green,
        points: 1,
        bonus: 1,
        ability: None,
        crowns: 0,
        cost: CardCost::new(3, 0, 0, 0, 2, 0),
    },
    JewelCard {
        id: 14,
        tier: CardTier::Tier1,
        color: CardColor::Green,
        points: 0,
        bonus: 1,
        ability: None,
        crowns: 1,
        cost: CardCost::new(0, 0, 0, 3, 0, 0),
    },
    JewelCard {
        id: 15,
        tier: CardTier::Tier1,
        color: CardColor::Blue,
        points: 0,
        bonus: 1,
        ability: None,
        crowns: 0,
        cost: CardCost::new(1, 0, 1, 1, 1, 0),
    },
    JewelCard {
        id: 16,
        tier: CardTier::Tier1,
        color: CardColor::Blue,
        points: 0,
        bonus: 1,
        ability: Some(CardAbility::ExtraTurn),
        crowns: 0,
        cost: CardCost::new(0, 0, 2, 2, 0, 1),
    },
    JewelCard {
        id: 17,
        tier: CardTier::Tier1,
        color: CardColor::Blue,
        points: 0,
        bonus: 1,
        ability: Some(CardAbility::TakeSameColor),
        crowns: 0,
        cost: CardCost::new(2, 0, 0, 0, 2, 0),
    },
    JewelCard {
        id: 18,
        tier: CardTier::Tier1,
        color: CardColor::Blue,
        points: 1,
        bonus: 1,
        ability: None,
        crowns: 0,
        cost: CardCost::new(0, 0, 0, 2, 3, 0),
    },
    JewelCard {
        id: 19,
        tier: CardTier::Tier1,
        color: CardColor::Blue,
        points: 0,
        bonus: 1,
        ability: None,
        crowns: 1,
        cost: CardCost::new(0, 0, 3, 0, 0, 0),
    },
    JewelCard {
        id: 20,
        tier: CardTier::Tier1,
        color: CardColor::White,
        points: 0,
        bonus: 1,
        ability: None,
        crowns: 0,
        cost: CardCost::new(0, 1, 1, 1, 1, 0),
    },
    JewelCard {
        id: 21,
        tier: CardTier::Tier1,
        color: CardColor::White,
        points: 0,
        bonus: 1,
        ability: Some(CardAbility::ExtraTurn),
        crowns: 0,
        cost: CardCost::new(0, 2, 2, 0, 0, 1),
    },
    JewelCard {
        id: 22,
        tier: CardTier::Tier1,
        color: CardColor::White,
        points: 0,
        bonus: 1,
        ability: Some(CardAbility::TakeSameColor),
        crowns: 0,
        cost: CardCost::new(0, 0, 0, 2, 2, 0),
    },
    JewelCard {
        id: 23,
        tier: CardTier::Tier1,
        color: CardColor::White,
        points: 1,
        bonus: 1,
        ability: None,
        crowns: 0,
        cost: CardCost::new(0, 0, 2, 3, 0, 0),
    },
    JewelCard {
        id: 24,
        tier: CardTier::Tier1,
        color: CardColor::White,
        points: 0,
        bonus: 1,
        ability: None,
        crowns: 1,
        cost: CardCost::new(0, 3, 0, 0, 0, 0),
    },
    JewelCard {
        id: 25,
        tier: CardTier::Tier1,
        color: CardColor::Points,
        points: 3,
        bonus: 0,
        ability: None,
        crowns: 0,
        cost: CardCost::new(0, 0, 0, 4, 0, 1),
    },
    JewelCard {
        id: 26,
        tier: CardTier::Tier1,
        color: CardColor::Joker,
        points: 1,
        bonus: 1,
        ability: Some(CardAbility::ColorCopy),
        crowns: 0,
        cost: CardCost::new(0, 0, 0, 0, 4, 1),
    },
    JewelCard {
        id: 27,
        tier: CardTier::Tier1,
        color: CardColor::Joker,
        points: 0,
        bonus: 1,
        ability: Some(CardAbility::ColorCopy),
        crowns: 1,
        cost: CardCost::new(4, 0, 0, 0, 0, 1),
    },
    JewelCard {
        id: 28,
        tier: CardTier::Tier1,
        color: CardColor::Joker,
        points: 1,
        bonus: 1,
        ability: Some(CardAbility::ColorCopy),
        crowns: 0,
        cost: CardCost::new(2, 0, 2, 0, 1, 1),
    },
    JewelCard {
        id: 29,
        tier: CardTier::Tier1,
        color: CardColor::Joker,
        points: 1,
        bonus: 1,
        ability: Some(CardAbility::ColorCopy),
        crowns: 0,
        cost: CardCost::new(0, 2, 0, 2, 1, 1),
    },
    JewelCard {
        id: 30,
        tier: CardTier::Tier2,
        color: CardColor::Black,
        points: 1,
        bonus: 1,
        ability: Some(CardAbility::StealToken),
        crowns: 0,
        cost: CardCost::new(4, 0, 3, 0, 0, 0),
    },
    JewelCard {
        id: 31,
        tier: CardTier::Tier2,
        color: CardColor::Black,
        points: 1,
        bonus: 2,
        ability: None,
        crowns: 0,
        cost: CardCost::new(5, 2, 0, 0, 0, 0),
    },
    JewelCard {
        id: 32,
        tier: CardTier::Tier2,
        color: CardColor::Black,
        points: 2,
        bonus: 1,
        ability: None,
        crowns: 1,
        cost: CardCost::new(0, 2, 2, 2, 0, 1),
    },
    JewelCard {
        id: 33,
        tier: CardTier::Tier2,
        color: CardColor::Black,
        points: 2,
        bonus: 1,
        ability: Some(CardAbility::TakePrivilege),
        crowns: 0,
        cost: CardCost::new(0, 0, 0, 2, 4, 1),
    },
    JewelCard {
        id: 34,
        tier: CardTier::Tier2,
        color: CardColor::Red,
        points: 1,
        bonus: 1,
        ability: Some(CardAbility::StealToken),
        crowns: 0,
        cost: CardCost::new(0, 3, 0, 0, 4, 0),
    },
    JewelCard {
        id: 35,
        tier: CardTier::Tier2,
        color: CardColor::Red,
        points: 1,
        bonus: 2,
        ability: None,
        crowns: 0,
        cost: CardCost::new(2, 0, 0, 0, 5, 0),
    },
    JewelCard {
        id: 36,
        tier: CardTier::Tier2,
        color: CardColor::Red,
        points: 2,
        bonus: 1,
        ability: None,
        crowns: 1,
        cost: CardCost::new(2, 2, 2, 0, 0, 1),
    },
    JewelCard {
        id: 37,
        tier: CardTier::Tier2,
        color: CardColor::Red,
        points: 2,
        bonus: 1,
        ability: Some(CardAbility::TakePrivilege),
        crowns: 0,
        cost: CardCost::new(0, 0, 2, 4, 0, 1),
    },
    JewelCard {
        id: 38,
        tier: CardTier::Tier2,
        color: CardColor::Green,
        points: 1,
        bonus: 1,
        ability: Some(CardAbility::StealToken),
        crowns: 0,
        cost: CardCost::new(3, 0, 0, 4, 0, 0),
    },
    JewelCard {
        id: 39,
        tier: CardTier::Tier2,
        color: CardColor::Green,
        points: 1,
        bonus: 2,
        ability: None,
        crowns: 0,
        cost: CardCost::new(0, 0, 0, 5, 2, 0),
    },
    JewelCard {
        id: 40,
        tier: CardTier::Tier2,
        color: CardColor::Green,
        points: 2,
        bonus: 1,
        ability: None,
        crowns: 1,
        cost: CardCost::new(2, 2, 0, 0, 2, 1),
    },
    JewelCard {
        id: 41,
        tier: CardTier::Tier2,
        color: CardColor::Green,
        points: 2,
        bonus: 1,
        ability: Some(CardAbility::TakePrivilege),
        crowns: 0,
        cost: CardCost::new(0, 2, 4, 0, 0, 1),
    },
    JewelCard {
        id: 42,
        tier: CardTier::Tier2,
        color: CardColor::Blue,
        points: 1,
        bonus: 1,
        ability: Some(CardAbility::StealToken),
        crowns: 0,
        cost: CardCost::new(0, 0, 4, 0, 3, 0),
    },
    JewelCard {
        id: 43,
        tier: CardTier::Tier2,
        color: CardColor::Blue,
        points: 1,
        bonus: 2,
        ability: None,
        crowns: 0,
        cost: CardCost::new(0, 0, 5, 2, 0, 0),
    },
    JewelCard {
        id: 44,
        tier: CardTier::Tier2,
        color: CardColor::Blue,
        points: 2,
        bonus: 1,
        ability: None,
        crowns: 1,
        cost: CardCost::new(2, 0, 0, 2, 2, 1),
    },
    JewelCard {
        id: 45,
        tier: CardTier::Tier2,
        color: CardColor::Blue,
        points: 2,
        bonus: 1,
        ability: Some(CardAbility::TakePrivilege),
        crowns: 0,
        cost: CardCost::new(2, 4, 0, 0, 0, 1),
    },
    JewelCard {
        id: 46,
        tier: CardTier::Tier2,
        color: CardColor::White,
        points: 1,
        bonus: 1,
        ability: Some(CardAbility::StealToken),
        crowns: 0,
        cost: CardCost::new(0, 4, 0, 3, 0, 0),
    },
    JewelCard {
        id: 47,
        tier: CardTier::Tier2,
        color: CardColor::White,
        points: 1,
        bonus: 2,
        ability: None,
        crowns: 0,
        cost: CardCost::new(0, 5, 2, 0, 0, 0),
    },
    JewelCard {
        id: 48,
        tier: CardTier::Tier2,
        color: CardColor::White,
        points: 2,
        bonus: 1,
        ability: None,
        crowns: 1,
        cost: CardCost::new(0, 0, 2, 2, 2, 1),
    },
    JewelCard {
        id: 49,
        tier: CardTier::Tier2,
        color: CardColor::White,
        points: 2,
        bonus: 1,
        ability: Some(CardAbility::TakePrivilege),
        crowns: 0,
        cost: CardCost::new(4, 0, 0, 0, 2, 1),
    },
    JewelCard {
        id: 50,
        tier: CardTier::Tier2,
        color: CardColor::Points,
        points: 5,
        bonus: 0,
        ability: None,
        crowns: 0,
        cost: CardCost::new(0, 6, 0, 0, 0, 1),
    },
    JewelCard {
        id: 51,
        tier: CardTier::Tier2,
        color: CardColor::Joker,
        points: 2,
        bonus: 1,
        ability: Some(CardAbility::ColorCopy),
        crowns: 0,
        cost: CardCost::new(0, 0, 6, 0, 0, 1),
    },
    JewelCard {
        id: 52,
        tier: CardTier::Tier2,
        color: CardColor::Joker,
        points: 0,
        bonus: 1,
        ability: Some(CardAbility::ColorCopy),
        crowns: 2,
        cost: CardCost::new(0, 0, 6, 0, 0, 1),
    },
    JewelCard {
        id: 53,
        tier: CardTier::Tier2,
        color: CardColor::Joker,
        points: 0,
        bonus: 1,
        ability: Some(CardAbility::ColorCopy),
        crowns: 2,
        cost: CardCost::new(0, 6, 0, 0, 0, 1),
    },
    JewelCard {
        id: 54,
        tier: CardTier::Tier3,
        color: CardColor::Black,
        points: 3,
        bonus: 1,
        ability: None,
        crowns: 2,
        cost: CardCost::new(3, 0, 5, 3, 0, 1),
    },
    JewelCard {
        id: 55,
        tier: CardTier::Tier3,
        color: CardColor::Black,
        points: 4,
        bonus: 1,
        ability: None,
        crowns: 0,
        cost: CardCost::new(2, 0, 0, 2, 6, 0),
    },
    JewelCard {
        id: 56,
        tier: CardTier::Tier3,
        color: CardColor::Red,
        points: 3,
        bonus: 1,
        ability: None,
        crowns: 2,
        cost: CardCost::new(0, 5, 3, 0, 3, 1),
    },
    JewelCard {
        id: 57,
        tier: CardTier::Tier3,
        color: CardColor::Red,
        points: 4,
        bonus: 1,
        ability: None,
        crowns: 0,
        cost: CardCost::new(0, 0, 2, 6, 2, 0),
    },
    JewelCard {
        id: 58,
        tier: CardTier::Tier3,
        color: CardColor::Green,
        points: 3,
        bonus: 1,
        ability: None,
        crowns: 2,
        cost: CardCost::new(5, 3, 0, 3, 0, 1),
    },
    JewelCard {
        id: 59,
        tier: CardTier::Tier3,
        color: CardColor::Green,
        points: 4,
        bonus: 1,
        ability: None,
        crowns: 0,
        cost: CardCost::new(0, 2, 6, 2, 0, 0),
    },
    JewelCard {
        id: 60,
        tier: CardTier::Tier3,
        color: CardColor::Blue,
        points: 3,
        bonus: 1,
        ability: None,
        crowns: 2,
        cost: CardCost::new(3, 0, 3, 0, 5, 1),
    },
    JewelCard {
        id: 61,
        tier: CardTier::Tier3,
        color: CardColor::Blue,
        points: 4,
        bonus: 1,
        ability: None,
        crowns: 0,
        cost: CardCost::new(2, 6, 2, 0, 0, 0),
    },
    JewelCard {
        id: 62,
        tier: CardTier::Tier3,
        color: CardColor::White,
        points: 3,
        bonus: 1,
        ability: None,
        crowns: 2,
        cost: CardCost::new(0, 3, 0, 5, 3, 1),
    },
    JewelCard {
        id: 63,
        tier: CardTier::Tier3,
        color: CardColor::White,
        points: 4,
        bonus: 1,
        ability: None,
        crowns: 0,
        cost: CardCost::new(6, 2, 0, 0, 2, 0),
    },
    JewelCard {
        id: 64,
        tier: CardTier::Tier3,
        color: CardColor::Points,
        points: 6,
        bonus: 0,
        ability: None,
        crowns: 0,
        cost: CardCost::new(8, 0, 0, 0, 0, 0),
    },
    JewelCard {
        id: 65,
        tier: CardTier::Tier3,
        color: CardColor::Joker,
        points: 0,
        bonus: 1,
        ability: Some(CardAbility::ColorCopy),
        crowns: 3,
        cost: CardCost::new(0, 0, 0, 0, 8, 0),
    },
    JewelCard {
        id: 66,
        tier: CardTier::Tier3,
        color: CardColor::Joker,
        points: 3,
        bonus: 1,
        ability: Some(CardAbility::ColorCopyAndExtraTurn),
        crowns: 0,
        cost: CardCost::new(0, 0, 0, 8, 0, 0),
    },
];

/// 全套 4 张王室卡静态数据库
pub const ALL_ROYAL_CARDS: [RoyalCard; 4] = [
    RoyalCard {
        id: 0,
        points: 2,
        ability: Some(RoyalAbility::StealToken),
    },
    RoyalCard {
        id: 1,
        points: 2,
        ability: Some(RoyalAbility::TakePrivilege),
    },
    RoyalCard {
        id: 2,
        points: 2,
        ability: Some(RoyalAbility::ExtraTurn),
    },
    RoyalCard {
        id: 3,
        points: 3,
        ability: None,
    },
];
